services:
  nginx:
    build:
      context: ./.docker/nginx/${NGINX_VERSION}
    ports:
      - 80:8000
    links:
      - phpfpm
      - redis:cache
    volumes:
      - ./magento:/var/www/html
      - ./services/sock_data:/sock
      - ./services/nginx_log:/var/log/nginx
      #- ./frontend/${FRONTEND_VENDOR_NAME}:/var/www/html/app/design/frontend/${FRONTEND_VENDOR_NAME}
      #- ./backend/${BACKEND_VENDOR_NAME}:/var/www/html/app/code/${BACKEND_VENDOR_NAME}
    networks:
      - magento

  phpfpm:
    build:
      context: ./.docker/php/${PHP_VERSION}
    links:
      - db
    volumes:
      - ./.docker/php/${PHP_VERSION}/.composer:/var/www/.composer
      - ./magento:/var/www/html
      - ./services/sock_data:/sock
      - ./services/phpfpm_log:/var/log
      #- ./frontend/${FRONTEND_VENDOR_NAME}:/var/www/html/app/design/frontend/${FRONTEND_VENDOR_NAME}
      #- ./backend/${BACKEND_VENDOR_NAME}:/var/www/html/app/code/${BACKEND_VENDOR_NAME}
    networks:
      - magento

  redis:
    image: redis:${REDIS_VERSION}
    restart: on-failure:5
    volumes:
      - ./services/redis_data:/data
    expose:
      - 6379
    networks:
      - magento

  db:
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command: ["--log_bin_trust_function_creators=1"]
    volumes:
      - ./services/mysql_data:/var/lib/mysql
      - ./services/mysql_log:/var/log/mysql
    ports:
      - 3306:3306
    networks:
      - magento

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - magento

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./services/es_data:/usr/share/elasticsearch/data
      - ./services/es_log:/var/log/elasticsearch
    ports:
      - 9200:9200
    networks:
      - magento

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    links:
      - phpfpm
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - magento

networks:
  magento:
    driver: bridge
